extends: relaxed

rules:
  comments:
    level: error
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  comments-indentation:
    level: error

  document-start:
    level: error
    present: false

  document-end:
    level: error
    present: false

  empty-lines:
    level: error
    max: 1

  indentation:
    level: error
    spaces: 2

  quoted-strings:
    quote-type: single
    required: only-when-needed

  line-length: disable
