name: Lint

on: pull_request

permissions:
  contents: read

jobs:
  actionlint:
    name: GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Lint GitHub Actions Workflow Files
        uses: docker://rhysd/actionlint@sha256:daa1edae4a6366f320b68abb60b74fb59a458c17b61938d3c62709d92b231558 # v1.6.27
        with:
          args: -color
  yamllint:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
      - name: Install yamllint
        run: |
          pip install --upgrade pip
          pip install yamllint
      - name: Lint YAML Files
        run: |
          yamllint .
  nix-flake-check:
    name: Nix Flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main # Using `main` as per the usage instructions.
      - name: nix flake check
        run: |
          nix flake check
